### ISSUE TITLE
 Removal of "banner" and "icon" columns from "apps" table?

### ISSUE THREAD

**Issue by tpdi** [CocoCR300/flauncher#14]
In 16e09d22aa8ddf4c5773666643a00d6e20b864b2 you (CocoCR300) removed "banner" and "icon" columns from "apps" table.

What was the rationale for that, and what are the consequences? I'm guessing these can be dynamically loaded from apps, and so we don't need then in the table?

I ask because I'm working at fixing the tests to being them up to date with your changes, and even after removing all (I think?) references to  "banner" and "icon", I'm getting a SQL exception when I run the migration tests, ironically that 'alter table drop column banner;' is failing. (For the remaining tests I've removed references to Crashlytics/Firebase and to code in WallpaperService and SettingsServie, that you changed.) Once the tests are fixed, I'll submit a PR, and an additional PR adding a setting to suppress the "keyclick" sound.

Thanks!

**Comment by CocoCR300** [comment]
First, thanks for your contributions.
You're right about loading the apps icon and banner "dynamically", I saw no reason to store those on the database, since one can get them from Android's PackageManager the same way as the rest of the apps info, they were just taking up the most amount of storage there.
I wasn't planning on fixing the tests so, sorry if I left a mess there, and thanks again!
I'll review your contributions now and try to release some new packages soon.
